public with sharing class RecursiveTriggerUtility {
    
    public static boolean isSicUpdate = false;
    public static boolean isOppSweep = false;
    public static boolean isSendEMailNotificationToBrnachManagar = false;
    public static boolean isNextTaskInfoLead = false;
    public static boolean isNextTaskInfoOpportunity = false;
    public static boolean isUpdateOpportunityOpenTasks = false;
    public static boolean isTaskLeadResponseTimeCalculation = false;
    public static boolean isAssignSalesRep = false;
    public static boolean isCampaignMemberManager = false;
    public static boolean isMaintainBranchAccounts = false;
    public static boolean isUpdateBranchCodeOpportunityBranchId = false;
    public static boolean isUpdateBranchCodeOpportunityServiceBranchId = false;
    public static boolean isUpdateservicingBranch = false;
    
    //---added for TFS 2368--------------------------
    public static Boolean isBranchCodeUserQueryCalled = false;
    public static Boolean isUpdateBranchCodeOpportunityCalled = false;
    
    //--------- added for DP-JP creation ------------------- 
    public static Boolean isJBcreationCalled = false;
    
}